version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 14...
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Testing...
      - jest -- unit
artifacts:
  files:
    - "**/*"
  discard-paths: no
